### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 10000

### ISSUE THREAD

**Issue by ahikmat85** [haven-jeon/KoNLP#26]
Hi,

I am getting this kind of error while processing a huge vector(1mln texts)

java.lang.ArrayIndexOutOfBoundsException: 10000
    at kr.ac.kaist.swrc.jhannanum.plugin.MajorPlugin.PosTagger.HmmPosTagger.KoNLPHMMTagger.new_mnode(KoNLPHMMTagger.java:349)
    at kr.ac.kaist.swrc.jhannanum.plugin.MajorPlugin.PosTagger.HmmPosTagger.KoNLPHMMTagger.tagPOS(KoNLPHMMTagger.java:140)
    at kr.ac.kaist.swrc.jhannanum.hannanum.Workflow.analyzeInSingleThread(Workflow.java:870)
    at kr.ac.kaist.swrc.jhannanum.hannanum.Workflow.analyze(Workflow.java:534)
    at kr.pe.freesearch.jhannanum.comm.HannanumInterface.extractNoun(HannanumInterface.java:141)

is there any way to fix this problem?

**Comment by e9t** [comment]
Thanks @ahikmat85 for reporting the issue! I would also like to replicate this error since [konlpy has the same problem](https://github.com/konlpy/konlpy/issues/9).

**Comment by haven-jeon** [comment]
I think this weired, because '# of Eojeol * # of tags' can not exceed 100,000 on normal **one** sentence. So, this problem was related with specific abnormal sentence, not size of text. 
I'm not sure I can get sentences you want to processe. 

Next version of KoNLP will resolve with strong sentence detection logic.
